@@ -0,0 +1,205 @@
---
title: "pitcheranalysis"
output: html_document
date: "2024-09-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
par(pin = c(12, 8))
```

```{r}
# Linking Scores to Datasets
# 2021 Season
if (!file.exists("data/pitchesWithScore21.csv") && !file.exists("data/pitchesWithScore22.csv") && !file.exists("data/pitchesWithScore23.csv")) {
  gamescore21 <- read.csv("data/gamescore_by_gameid_ab/gameid_ab_score_21.csv")
  pitches21 <- read.csv("data/pitches_21.csv")
  pitchwithscore21 <- left_join(pitches21,gamescore21, join_by(gameid,ab)) # joining score to pitches21
  
  # 2022 Season
  gamescore22 <- read.csv("data/gamescore_by_gameid_ab/gameid_ab_score_22.csv")
  pitches22 <- read.csv("data/pitches_22.csv")
  pitchwithscore22 <- left_join(pitches22,gamescore22, join_by(gameid,ab)) # joining score to pitches21
  
  # 2023 Season
  gamescore23 <- read.csv("data/gamescore_by_gameid_ab/gameid_ab_score_23.csv")
  pitches23 <- read.csv("data/pitches_23.csv")
  pitchwithscore23 <- left_join(pitches23,gamescore23, join_by(gameid,ab)) # joining score to pitches21
  
  write_csv(pitchwithscore21, "data/pitchesWithScore21.csv")
  write_csv(pitchwithscore22, "data/pitchesWithScore22.csv")
  write_csv(pitchwithscore23, "data/pitchesWithScore23.csv")
}
```

## Closer EDA

#### Build Closer Datasets Per Year

```{r}
# Closers | 2021 season 
pitchwithscore21$closeness <- abs(pitchwithscore21$homscore - pitchwithscore21$visscore)
#filtering by closeness and whether the pitcher is closing
datawscore21<- filter(pitchwithscore21, closeness<=3, inning>=8)
#examining espn's top closers
espnbest21 <- c("Melancon, Mark", "Hendriks, Liam", "Jansen, Kenley", "Smith, Will", "Iglesias, Raisel", "Hader, Josh", "Diaz, Edwin", "McGee, Jake", "Chapman, Aroldis", "Reyes, Alex", "Pressly, Ryan", "Clase, Emmanuel", "Barnes, Matt", "Romano, Jordan", "Kimbrel, Craig", "Trivino, Lou", "Hand, Brad", "Bard, Daniel", "Soto, Gregory","Colome, Alex", "Barlow, Scott", "Kennedy, Ian", "Floro, Dylan", "Steckenrider, Drew", "Rodriguez, Richard", "Castillo, Diego", "Neris, Hector", "Sulser, Cole", "Hembree, Heath", "Soria, Joakim")
#above from https://www.espn.com/mlb/stats/closers/_/year/2021
espnsbestclosers21<- filter(pitchwithscore21, closeness<=3, inning>=8, pitcher %in% espnbest21)
```

```{r}
# Closers | 2022 season
pitchwithscore22$closeness <- abs(pitchwithscore22$homscore - pitchwithscore22$visscore)
#filtering by closeness and whether the pitcher is closing
datawscore22<- filter(pitchwithscore22, closeness<=3, inning>=8)
#examining espn's top closers
espnbest22 <- c("Clase, Emmanuel", "Jansen, Kenley", "Hendriks, Liam", "Romano, Jordan", "Bard, Daniel", "Pressly, Ryan", "Diaz, Edwin", "Soto, Gregory", "Hader, Josh", "Rogers, Taylor", "Doval, Camilo", "Barlow, Scott", "Kimbrel, Craig", "Sewald, Paul", "Holmes, Clay", "Scott, Tanner", "Helsley, Ryan", "Bednar, David", "Lopez, Jorge", "Melancon, Mark", "Iglesias, Raisel", "Robertson, David", "Barlow, Joe", "Knebel, Corey", "Rainey, Tanner", "Jimenez, Dany", "Diaz, Alexis", "Pagan, Emilio", "Schreiber, John")
espnsbestclosers22<- filter(pitchwithscore22, closeness<=3, inning>=8, pitcher %in% espnbest22)
```

```{r}
# Closers | 2023 season
pitchwithscore23$closeness <- abs(pitchwithscore23$homscore - pitchwithscore23$visscore)
#filtering by closeness and whether the pitcher is closing
datawscore23<- filter(pitchwithscore23, closeness<=3, inning>=8)
#examining espn's top closers
espnbest23 <- c("Clase, Emmanuel", "Bednar, David", "Doval, Camilo", "Diaz, Alexis", "Romano, Jordan", "Williams, Devin", "Bautista, Felix", "Hader, Josh", "Iglesias, Raisel", "Pressly, Ryan", "Estevez, Carlos", "Jansen, Kenley", "Finnegan, Kyle", "Duran, Jhoan", "Lange, Alex", "Fairbanks, Pete", "Holmes, Clay", "Phillips, Evan", "Kimbrel, Craig", "Alzolay, Adbert", "Smith, Will", "May, Trevor", "Sewald, Paul", "Puk, A.J.", "Robertson, David", "Helsley, Ryan", "Johnson, Pierce", "Barlow, Scott", "Sewald, Paul", "Graveman, Kendall")
espnsbestclosers23<- filter(pitchwithscore23, closeness<=3, inning>=8, pitcher %in% espnbest23)
```

#### Combined Dataset

```{r}
all_closer_data<- rbind(espnsbestclosers21, espnsbestclosers22, espnsbestclosers23) %>% select(-X)
```

### Closer Pitch Type Frequency

```{r}
# ALL CLOSER DATA: Get each pitch type, plot frequencies, boxplot for pitching stats
all_closer_pitchtypes <- unique(all_closer_data$pitchname)
all_closer_pitchdesc <- unique(all_closer_data$pitchname_desc)
print(all_closer_pitchtypes)
print(all_closer_pitchdesc)
ggplot(data=all_closer_data, mapping = aes(x = pitchname))  +
  geom_bar() + xlab("Pitch Type") + ylab("Frequency") + ggtitle("Pitch Type Frequency for Closers from 2021-2023")
# Four-seam FB
all_closer_ff <- filter(all_closer_data, pitchname=="FF")
boxplot(scale(select(all_closer_ff, spinrate, relspeed, horzbreak, inducedvertbreak, platelocside, platelocheight)), ylab = "Standardized Values", las = 2, cex.axis = 0.8)
title("Fastball Pitching Stats Boxplots")
# Sinker
all_closer_si <- filter(all_closer_data, pitchname=="SI")
boxplot(scale(select(all_closer_si, spinrate, relspeed, horzbreak, inducedvertbreak, platelocside, platelocheight)), ylab = "Standardized Values", las = 2, cex.axis = 0.8)
title("Sinker Pitching Stats Boxplots")
# Slider
all_closer_sl <- filter(all_closer_data, pitchname=="SL")
boxplot(scale(select(all_closer_sl, spinrate, relspeed, horzbreak, inducedvertbreak, platelocside, platelocheight)), ylab = "Standardized Values", las = 2, cex.axis = 0.8)
title("Slider Pitching Stats Boxplots")
# Curveball
all_closer_cu <- filter(all_closer_data, pitchname=="CU")
boxplot(scale(select(all_closer_cu, spinrate, relspeed, horzbreak, inducedvertbreak, platelocside, platelocheight)), ylab = "Standardized Values", las = 2, cex.axis = 0.8)
title("Curveball Pitching Stats Boxplots")
# Changeup
all_closer_ch <- filter(all_closer_data, pitchname=="CH")
boxplot(scale(select(all_closer_ch, spinrate, relspeed, horzbreak, inducedvertbreak, platelocside, platelocheight)), ylab = "Standardized Values", las = 2, cex.axis = 0.8)
title("Changeup Pitching Stats Boxplots")
# Cutter
all_closer_fc <- filter(all_closer_data, pitchname=="FC")
boxplot(scale(select(all_closer_fc, spinrate, relspeed, horzbreak, inducedvertbreak, platelocside, platelocheight)), ylab = "Standardized Values", las = 2, cex.axis = 0.8)
title("Cutter Pitching Stats Boxplots")
# Splitter
all_closer_fs <- filter(all_closer_data, pitchname=="FS")
boxplot(scale(select(all_closer_fs, spinrate, relspeed, horzbreak, inducedvertbreak, platelocside, platelocheight)), ylab = "Standardized Values", las = 2, cex.axis = 0.8)
title("Splitter Pitching Stats Boxplots")
# Knuckle Curve
all_closer_kc <- filter(all_closer_data, pitchname=="KC")
boxplot(scale(select(all_closer_kc, spinrate, relspeed, horzbreak, inducedvertbreak, platelocside, platelocheight)), ylab = "Standardized Values", las = 2, cex.axis = 0.8)
title("Knuckle Curve Pitching Stats Boxplots")
# Sweeper
all_closer_st <- filter(all_closer_data, pitchname=="ST")
boxplot(scale(select(all_closer_st, spinrate, relspeed, horzbreak, inducedvertbreak, platelocside, platelocheight)), ylab = "Standardized Values", las = 2, cex.axis = 0.8)
title("Sweeper Pitching Stats Boxplots")
```

### Individual Closer Datasets

```{r}
# vector of all closing pitchers (not used right now)
every_closer <- unique(c(espnbest21, espnbest22, espnbest23)) 

pitcherName <- paste0(all_closer_data$pitcher, " table")

#closer_tables is a list of tables
closer_tables <- split(all_closer_data,pitcherName)

avg_by_pitcher <- data.frame(matrix(ncol=8,nrow=0, dimnames=list(NULL, c("name", "pitch", "avg_spin", "avg_velo", "avg_hbreak", "avg_vbreak", "avg_plside", "avg_plheight"))))

for (i in closer_tables) {
  pitchtypes <- unique(i$pitchname)
  pitchdesc <- unique(i$pitchname_desc)
  table_by_pitch <- split(i, pitchtypes)
  for (j in table_by_pitch) {
    avg_spin <- j$spinrate
    avg_velo <- j$relspeed
    avg_hbreak <- j$horzbreak
    avg_vbreak <- j$inducedvertbreak
    avg_plside <- j$platelocside
    avg_plheight <- j$platelocheight
    avg_by_pitcher[nrow(avg_by_pitcher) + 1,] <- list(i[1,10], j[1,17], avg_spin, avg_velo, avg_hbreak, avg_vbreak, avg_plside, avg_plheight)
  }
  title_name <- paste((i[1,10]), "Pitch Type Frequency", sep = " ")
  print(ggplot(data=i, mapping = aes(x = pitchname))  +
  geom_bar() + xlab("Pitch Type") + ylab("Frequency") + ggtitle(title_name))
}

print(avg_by_pitcher)

```

```{r}
ind_closer_mean_ff <- filter(avg_by_pitcher, pitch=="FF")
boxplot(scale(select(ind_closer_mean_ff, avg_spin, avg_velo, avg_hbreak, avg_vbreak, avg_plside, avg_plheight)), ylab = "Standardized Values", las = 2, cex.axis = 0.8)
title("Fastball Pitching Stats Boxplots")
# Sinker
ind_closer_mean_si <- filter(avg_by_pitcher, pitch=="SI")
boxplot(scale(select(ind_closer_mean_si, avg_spin, avg_velo, avg_hbreak, avg_vbreak, avg_plside, avg_plheight)), ylab = "Standardized Values", las = 2, cex.axis = 0.8)
title("Sinker Pitching Stats Boxplots")
# Slider
ind_closer_mean_sl <- filter(avg_by_pitcher, pitch=="SL")
boxplot(scale(select(ind_closer_mean_sl, avg_spin, avg_velo, avg_hbreak, avg_vbreak, avg_plside, avg_plheight)), ylab = "Standardized Values", las = 2, cex.axis = 0.8)
title("Slider Pitching Stats Boxplots")
# Curveball
ind_closer_mean_cu <- filter(avg_by_pitcher, pitch=="CU")
boxplot(scale(select(ind_closer_mean_cu, avg_spin, avg_velo, avg_hbreak, avg_vbreak, avg_plside, avg_plheight)), ylab = "Standardized Values", las = 2, cex.axis = 0.8)
title("Curveball Pitching Stats Boxplots")
# Changeup
ind_closer_mean_ch <- filter(avg_by_pitcher, pitch=="CH")
boxplot(scale(select(ind_closer_mean_ch, avg_spin, avg_velo, avg_hbreak, avg_vbreak, avg_plside, avg_plheight)), ylab = "Standardized Values", las = 2, cex.axis = 0.8)
title("Changeup Pitching Stats Boxplots")
# Cutter
ind_closer_mean_fc <- filter(avg_by_pitcher, pitch=="FC")
boxplot(scale(select(ind_closer_mean_fc, avg_spin, avg_velo, avg_hbreak, avg_vbreak, avg_plside, avg_plheight)), ylab = "Standardized Values", las = 2, cex.axis = 0.8)
title("Cutter Pitching Stats Boxplots")
# Splitter
ind_closer_mean_fs <- filter(avg_by_pitcher, pitch=="FS")
boxplot(scale(select(ind_closer_mean_fs, avg_spin, avg_velo, avg_hbreak, avg_vbreak, avg_plside, avg_plheight)), ylab = "Standardized Values", las = 2, cex.axis = 0.8)
title("Splitter Pitching Stats Boxplots")
# Knuckle Curve
ind_closer_mean_kc <- filter(avg_by_pitcher, pitch=="KC")
boxplot(scale(select(ind_closer_mean_kc, avg_spin, avg_velo, avg_hbreak, avg_vbreak, avg_plside, avg_plheight)), ylab = "Standardized Values", las = 2, cex.axis = 0.8)
title("Knuckle Curve Pitching Stats Boxplots")
# Sweeper has only 1 pitcher who throws it, outlier on its own
```


## Reliever EDA

```{r}
# Group each individual game together (by game id or game date)
# Get all pitchers for home and away team in order
# Remove first pitcher and then ensure none of datapoints in closer set.
# Minimum threshold for number of appearances to exclude teams using starting pitchers.
# 2021 Relievers
pitch_order_2021 <- pitchwithscore21 %>%
  group_by(gameid, teambat) %>%
  arrange(ab) %>%  # Arrange by the order of at-bats or appearances
  summarise(
    pitcher_order = list(unique(pitcher)[-1])
  )
# Filtering the original dataset based on the pitcher list
reliever_2021 <- pitchwithscore21 %>%
  group_by(gameid, teambat) %>%
  filter(pitcher %in% unlist(pitch_order_2021$pitcher_order[match(gameid, pitch_order_2021$gameid)])) %>% # make sure it's a pitcher in this list. 
   filter(!(pitcher %in% espnbest21))
# 2022 Relievers
pitch_order_2022 <- pitchwithscore22 %>%
  group_by(gameid, teambat) %>%
  arrange(ab) %>%  # Arrange by the order of at-bats or appearances
  summarise(
    pitcher_order = list(unique(pitcher)[-1])
  )
# Filtering the original dataset based on the pitcher list
reliever_2022 <- pitchwithscore22 %>%
  group_by(gameid, teambat) %>%
  filter(pitcher %in% unlist(pitch_order_2022$pitcher_order[match(gameid, pitch_order_2022$gameid)])) %>% # make sure it's a pitcher in this list. 
   filter(!(pitcher %in% espnbest22))
# 2023 Relievers
pitch_order_2023 <- pitchwithscore23 %>%
  group_by(gameid, teambat) %>%
  arrange(ab) %>%  # Arrange by the order of at-bats or appearances
  summarise(
    pitcher_order = list(unique(pitcher)[-1])
  )
# Filtering the original dataset based on the pitcher list
reliever_2023 <- pitchwithscore23 %>%
  group_by(gameid, teambat) %>%
  filter(pitcher %in% unlist(pitch_order_2023$pitcher_order[match(gameid, pitch_order_2023$gameid)])) %>% # make sure it's a pitcher in this list. 
   filter(!(pitcher %in% espnbest23))
  
```

```{r}
#location of pitches groups by pitch type
ggplot(datawscore21, aes(x=platelocside, y= platelocheight)) + geom_point(alpha = 0.1)+ 
  facet_grid(pitchname~.)

#examining if the location of pitches is dependent on handedness of pitcher
ggplot(datawscore21, aes(x=platelocside, y= platelocheight)) + geom_point(alpha = 0.1)+ 
  facet_grid(pitchname~pitcherthrows)

#are any ambidextrous? no
sum(datawscore21$pitcherthrows=="R")
sum(datawscore21$pitcherthrows=="L")
sum(datawscore21$pitcherthrows=="R" & datawscore21$pitcherthrows=="L")

sum(datawscore21$batterside=="R")
sum(datawscore21$batterside=="L")
sum(datawscore21$batterside=="R" & datawscore21$batterside=="L")

#finding the frequency of each pitch type and their result
datawscore21_count <- datawscore21 %>%
  group_by(pitchname, pitchresult, pitcherthrows, batterside) %>%
  summarize(count = n())  # Calculate the frequency of each combination

ggplot(datawscore21_count, aes(x = pitchname, y = pitchresult, size = count)) +
  geom_point(alpha = 0.6) +  
  scale_size_continuous(range = c(1, 10))

ggplot(datawscore21_count, aes(x=pitchname, y= pitchresult, size =count)) + geom_point(alpha = 0.3)+
    scale_size(range = c(.1, 24)) #overall

ggplot(datawscore21_count, aes(x=pitchname, y= pitchresult, size =count)) +
  geom_point(alpha = 0.3)+
  scale_size(range = c(.1, 24))+ 
  facet_grid(pitcherthrows~batterside) #impact of handedness


```

```{r}
total_counts <- data %>%
  group_by(balls, strikes) %>%
  summarise(total = n(), .groups = "drop")

# Aggregate the data by pitch type, ball, and strike count
aggregated_data <- data %>%
  group_by(pitchname_desc, balls, strikes) %>%
  summarise(count = n(), .groups = "drop") %>%
  left_join(total_counts, by = c("balls", "strikes")) %>%  # Join to get total counts
  mutate(proportion = count / total)  # Calculate proportion

pitch_types <- unique(aggregated_data$pitchname_desc)

for (pitch_type in pitch_types) {
  # Create the plot for the current pitch type
  plot <- ggplot(aggregated_data %>% filter(pitchname_desc == pitch_type), 
                 aes(x = balls, y = strikes, fill = proportion)) +
    geom_tile() +
    scale_fill_gradient(low = "white", high = "red") +
    labs(
      title = paste0("Heatmap of ", pitch_type, " by Ball and Strike Count (Proportions)"),
      x = "Ball Count",
      y = "Strike Count",
      fill = "Proportion"
    ) +
    theme_minimal()

  # Display the plot (optional)
  print(plot)
}
```

